const blue = "rgba(0,194,224,.7)",
  orange = "rgba(250,146,63,.7)",
  green = "rgba(20,102,24,.6)",
  fuschia = "rgba(221,33,83,.6)",
  goldenrod = "rgba(218,165,33,.7)",
  purple = "rgba(192,63,230,.7)"

const headingData = [
  {
    text: "t",
    left: 15,
    top: 18,
    display: "inline-block",
    direction: "across",
    colour: blue,
    word: "tompiler",
    colour2: orange,
    word2: "tutorials",
  },
  {
    text: "ompile",
    left: 17.5,
    top: 18,
    display: "inline-block",
    direction: "across",
    colour: blue,
    word: "tompiler",
  },
  {
    text: "r",
    left: 32.5,
    top: 18,
    display: "inline-block",
    direction: "across",
    colour: blue,
    word: "tompiler",
    colour2: fuschia,
    word2: "articles",
  },
  {
    text: "u",
    left: 15,
    top: 24.1,
    display: "inline-block",
    direction: "down",
    colour: orange,
    word: "tutorials",
  },
  {
    text: "t",
    left: 15,
    top: 30.4,
    display: "inline-block",
    direction: "down",
    colour: orange,
    word: "tutorials",
    colour2: green,
    word2: "contact",
  },
  {
    text: "ori",
    left: 15,
    top: 36.6,
    display: "inline-block",
    direction: "down",
    colour: orange,
    word: "tutorials",
  },
  {
    text: "a",
    left: 15,
    top: 55.1,
    display: "inline-block",
    direction: "down",
    colour: orange,
    word: "tutorials",
    colour2: blue,
    word2: "about",
  },
  {
    text: "ls",
    left: 15,
    top: 61.2,
    display: "inline-block",
    direction: "down",
    colour: orange,
    word: "tutorials",
  },
  {
    text: "c",
    left: 7.5,
    top: 30.35,
    display: "inline-block",
    direction: "across",
    colour: green,
    word: "contact",
    colour2: goldenrod,
    word2: "cv",
  },
  {
    text: "on",
    left: 10.0,
    top: 30.35,
    display: "inline-block",
    direction: "across",
    colour: green,
    word: "contact",
  },
  {
    text: "act",
    left: 17.5,
    top: 30.35,
    display: "inline-block",
    direction: "across",
    colour: green,
    word: "contact",
  },
  {
    text: "v",
    left: 7.5,
    top: 36.5,
    display: "inline-block",
    direction: "down",
    colour: goldenrod,
    word: "cv",
  },
  {
    text: "a",
    left: 32.5,
    top: 11.82,
    display: "inline-block",
    direction: "down",
    colour: fuschia,
    word: "articles",
  },
  {
    text: "ticles",
    left: 32.5,
    top: 24.1,
    display: "inline-block",
    direction: "down",
    colour: fuschia,
    word: "articles",
  },
  {
    text: "bout",
    left: 17.5,
    top: 55.1,
    display: "inline-block",
    direction: "across",
    colour: blue,
    word: "about",
  },
]

export default headingData
