const /*blue = "rgba(0,194,224,.9)",*/
  blue = { red: 74, green: 171, blue: 255, a: 0.7 },
  orange = { red: 250, green: 146, blue: 63, a: 0.7 },
  green = { red: 20, green: 102, blue: 24, a: 0.5 },
  fuschia = { red: 221, green: 33, blue: 83, a: 0.6 }
// goldenrod = { red: 218, green: 165, blue: 33, a: 1 },
// purple = { red: 169, green: 39, blue: 207, a: 1 }

const headingData = {
  tompiler: [
    {
      text: "t",
      left: 15,
      top: 18,
      display: "inline-block",
      direction: "across",
      colour: blue,
      word: "tompiler",
    },
    {
      text: "o",
      left: 15,
      top: 24,
      display: "inline-block",
      direction: "across",
      colour: blue,
      word: "tompiler",
    },
    {
      text: "m",
      left: 15,
      top: 30,
      display: "inline-block",
      direction: "across",
      colour: blue,
      word: "tompiler",
    },
  ],
  tutorials: [
    {
      text: "t",
      left: 25,
      top: 18,
      display: "inline-block",
      direction: "across",
      colour: orange,
      word: "tutorials",
    },
    {
      text: "u",
      left: 25,
      top: 24,
      display: "inline-block",
      direction: "across",
      colour: orange,
      word: "tutorials",
    },
    {
      text: "t",
      left: 25,
      top: 30,
      display: "inline-block",
      direction: "across",
      colour: orange,
      word: "tutorials",
    },
  ],
  contact: [
    {
      text: "c",
      left: 35,
      top: 18,
      display: "inline-block",
      direction: "across",
      colour: green,
      word: "contact",
    },

    {
      text: "o",
      left: 35,
      top: 24,
      display: "inline-block",
      direction: "across",
      colour: green,
      word: "contact",
    },
    {
      text: "n",
      left: 35,
      top: 30,
      display: "inline-block",
      direction: "down",
      colour: green,
      word: "contact",
    },
  ],
  articles: [
    {
      text: "a",
      left: 40,
      top: 18,
      display: "inline-block",
      direction: "down",
      colour: fuschia,
      word: "articles",
    },

    {
      text: "r",
      left: 40,
      top: 24,
      display: "inline-block",
      direction: "down",
      colour: fuschia,
      word: "articles",
    },
    {
      text: "t",
      left: 40,
      top: 30,
      display: "inline-block",
      direction: "down",
      colour: fuschia,
      word: "articles",
    },
  ],
}

// const headingData = [
//   {
//     text: "t",
//     left: 15,
//     top: 18,
//     display: "inline-block",
//     direction: "across",
//     colour: blue,
//     word: "tompiler",
//     colour2: orange,
//     word2: "tutorials",
//   },
//   {
//     text: "ompile",
//     left: 17.5,
//     top: 18,
//     display: "inline-block",
//     direction: "across",
//     colour: blue,
//     word: "tompiler",
//   },
//   {
//     text: "r",
//     left: 32.5,
//     top: 18,
//     display: "inline-block",
//     direction: "across",
//     colour: blue,
//     word: "tompiler",
//     colour2: fuschia,
//     word2: "articles",
//   },
//   {
//     text: "u",
//     left: 15,
//     top: 24.1,
//     display: "inline-block",
//     direction: "down",
//     colour: orange,
//     word: "tutorials",
//   },
//   {
//     text: "t",
//     left: 15,
//     top: 30.35,
//     display: "inline-block",
//     direction: "down",
//     colour: orange,
//     word: "tutorials",
//     colour2: green,
//     word2: "contact",
//   },
//   {
//     text: "or",
//     left: 15,
//     top: 36.5,
//     display: "inline-block",
//     direction: "down",
//     colour: orange,
//     word: "tutorials",
//   },
//   {
//     text: "i",
//     left: 15,
//     top: 48.9,
//     display: "inline-block",
//     direction: "down",
//     colour: orange,
//     word: "tutorials",
//     colour2: purple,
//     word2: "mission",
//   },
//   {
//     text: "als",
//     left: 15,
//     top: 55.1,
//     display: "inline-block",
//     direction: "down",
//     colour: orange,
//     word: "tutorials",
//   },
//   {
//     text: "c",
//     left: 7.5,
//     top: 30.35,
//     display: "inline-block",
//     direction: "across",
//     colour: green,
//     word: "contact",
//     colour2: goldenrod,
//     word2: "cv",
//   },
//   {
//     text: "on",
//     left: 10.0,
//     top: 30.35,
//     display: "inline-block",
//     direction: "across",
//     colour: green,
//     word: "contact",
//   },
//   {
//     text: "act",
//     left: 17.5,
//     top: 30.35,
//     display: "inline-block",
//     direction: "across",
//     colour: green,
//     word: "contact",
//   },
//   {
//     text: "v",
//     left: 7.5,
//     top: 36.5,
//     display: "inline-block",
//     direction: "down",
//     colour: goldenrod,
//     word: "cv",
//   },
//   {
//     text: "a",
//     left: 32.5,
//     top: 11.82,
//     display: "inline-block",
//     direction: "down",
//     colour: fuschia,
//     word: "articles",
//   },
//   {
//     text: "ticles",
//     left: 32.5,
//     top: 24.1,
//     display: "inline-block",
//     direction: "down",
//     colour: fuschia,
//     word: "articles",
//   },
//   {
//     text: "m",
//     left: 12.5,
//     top: 48.9,
//     display: "inline-block",
//     direction: "across",
//     colour: purple,
//     word: "mission",
//   },
//   {
//     text: "ssion",
//     left: 17.5,
//     top: 48.9,
//     display: "inline-block",
//     direction: "across",
//     colour: purple,
//     word: "mission",
//   },
// ]

export default headingData
