const /*blue = "rgba(0,194,224,.9)",*/
  blue = { red: 74, green: 171, blue: 255, a: 0.7 },
  orange = { red: 250, green: 146, blue: 63, a: 0.7 },
  green = { red: 16, green: 120, blue: 53, a: 0.7 },
  fuschia = { red: 221, green: 33, blue: 83, a: 0.6 },
  goldenrod = { red: 245, green: 200, blue: 20, a: 0.6 },
  purple = { red: 169, green: 39, blue: 207, a: 0.6 }

const headingData = {
  tompiler: [
    {
      text: "t",
      left: 15,
      top: 18,
      display: "inline-block",
      direction: "across",
      colour: blue,
      word: "tompiler",
      colour2: orange,
      word2: "tutorials",
    },
    {
      text: "o",
      left: 17.2,
      top: 18,
      display: "inline-block",
      direction: "across",
      colour: blue,
      word: "tompiler",
    },
    {
      text: "m",
      left: 19.45,
      top: 18,
      display: "inline-block",
      direction: "across",
      colour: blue,
      word: "tompiler",
    },
    {
      text: "p",
      left: 21.7,
      top: 18,
      display: "inline-block",
      direction: "across",
      colour: blue,
      word: "tompiler",
    },
    {
      text: "i",
      left: 23.95,
      top: 18,
      display: "inline-block",
      direction: "across",
      colour: blue,
      word: "tompiler",
    },
    {
      text: "l",
      left: 26.2,
      top: 18,
      display: "inline-block",
      direction: "across",
      colour: blue,
      word: "tompiler",
    },
    {
      text: "e",
      left: 28.45,
      top: 18,
      display: "inline-block",
      direction: "across",
      colour: blue,
      word: "tompiler",
    },
    {
      text: "r",
      left: 30.7,
      top: 18,
      display: "inline-block",
      direction: "across",
      colour: blue,
      word: "tompiler",
      colour2: fuschia,
      word2: "articles",
    },
  ],
  tutorials: [
    {
      text: "u",
      left: 15,
      top: 24.3,
      display: "inline-block",
      direction: "down",
      colour: orange,
      word: "tutorials",
    },
    {
      text: "t",
      left: 15,
      top: 30.6,
      display: "inline-block",
      direction: "down",
      colour: orange,
      word: "tutorials",
      colour2: green,
      word2: "contact",
    },
    {
      text: "o",
      left: 15,
      top: 36.9,
      display: "inline-block",
      direction: "down",
      colour: orange,
      word: "tutorials",
    },
    {
      text: "r",
      left: 15,
      top: 43.2,
      display: "inline-block",
      direction: "down",
      colour: orange,
      word: "tutorials",
    },
    {
      text: "i",
      left: 15,
      top: 49.5,
      display: "inline-block",
      direction: "down",
      colour: orange,
      word: "tutorials",
      colour2: purple,
      word2: "mission",
    },
    {
      text: "a",
      left: 15,
      top: 55.8,
      display: "inline-block",
      direction: "down",
      colour: orange,
      word: "tutorials",
    },
    {
      text: "l",
      left: 15,
      top: 62.1,
      display: "inline-block",
      direction: "down",
      colour: orange,
      word: "tutorials",
    },
    {
      text: "s",
      left: 15,
      top: 68.4,
      display: "inline-block",
      direction: "down",
      colour: orange,
      word: "tutorials",
    },
  ],
  contact: [
    {
      text: "c",
      left: 8.4,
      top: 30.6,
      display: "inline-block",
      direction: "across",
      colour: green,
      word: "contact",
      colour2: goldenrod,
      word2: "cv",
    },

    {
      text: "o",
      left: 10.6,
      top: 30.6,
      display: "inline-block",
      direction: "across",
      colour: green,
      word: "contact",
    },
    {
      text: "n",
      left: 12.8,
      top: 30.6,
      display: "inline-block",
      direction: "across",
      colour: green,
      word: "contact",
    },
    {
      text: "a",
      left: 17.2,
      top: 30.6,
      display: "inline-block",
      direction: "across",
      colour: green,
      word: "contact",
    },
    {
      text: "c",
      left: 19.4,
      top: 30.6,
      display: "inline-block",
      direction: "across",
      colour: green,
      word: "contact",
    },
    {
      text: "t",
      left: 21.6,
      top: 30.6,
      display: "inline-block",
      direction: "across",
      colour: green,
      word: "contact",
    },
  ],
  articles: [
    {
      text: "a",
      left: 30.7,
      top: 11.7,
      display: "inline-block",
      direction: "down",
      colour: fuschia,
      word: "articles",
    },
    {
      text: "t",
      left: 30.7,
      top: 24.3,
      display: "inline-block",
      direction: "down",
      colour: fuschia,
      word: "articles",
    },
    {
      text: "i",
      left: 30.7,
      top: 30.6,
      display: "inline-block",
      direction: "down",
      colour: fuschia,
      word: "articles",
    },
    {
      text: "c",
      left: 30.7,
      top: 36.9,
      display: "inline-block",
      direction: "down",
      colour: fuschia,
      word: "articles",
    },
    {
      text: "l",
      left: 30.7,
      top: 43.2,
      display: "inline-block",
      direction: "down",
      colour: fuschia,
      word: "articles",
    },
    {
      text: "e",
      left: 30.7,
      top: 49.5,
      display: "inline-block",
      direction: "down",
      colour: fuschia,
      word: "articles",
    },
    {
      text: "s",
      left: 30.7,
      top: 55.8,
      display: "inline-block",
      direction: "down",
      colour: fuschia,
      word: "articles",
    },
  ],
  mission: [
    {
      text: "m",
      left: 12.8,
      top: 49.5,
      display: "inline-block",
      direction: "across",
      colour: purple,
      word: "mission",
    },
    {
      text: "s",
      left: 17.2,
      top: 49.5,
      display: "inline-block",
      direction: "across",
      colour: purple,
      word: "mission",
    },
    {
      text: "s",
      left: 19.4,
      top: 49.5,
      display: "inline-block",
      direction: "across",
      colour: purple,
      word: "mission",
    },
    {
      text: "i",
      left: 21.6,
      top: 49.5,
      display: "inline-block",
      direction: "across",
      colour: purple,
      word: "mission",
    },
    {
      text: "o",
      left: 23.8,
      top: 49.5,
      display: "inline-block",
      direction: "across",
      colour: purple,
      word: "mission",
    },
    {
      text: "n",
      left: 26.0,
      top: 49.5,
      display: "inline-block",
      direction: "across",
      colour: purple,
      word: "mission",
    },
  ],
  cv: [
    {
      text: "v",
      left: 8.4,
      top: 36.9,
      display: "inline-block",
      direction: "down",
      colour: goldenrod,
      word: "cv",
    },
  ],
}

// const headingData = [
//   {
//     text: "t",
//     left: 15,
//     top: 18,
//     display: "inline-block",
//     direction: "across",
//     colour: blue,
//     word: "tompiler",
//     colour2: orange,
//     word2: "tutorials",
//   },
//   {
//     text: "ompile",
//     left: 17.5,
//     top: 18,
//     display: "inline-block",
//     direction: "across",
//     colour: blue,
//     word: "tompiler",
//   },
//   {
//     text: "r",
//     left: 32.5,
//     top: 18,
//     display: "inline-block",
//     direction: "across",
//     colour: blue,
//     word: "tompiler",
//     colour2: fuschia,
//     word2: "articles",
//   },
//   {
//     text: "u",
//     left: 15,
//     top: 24.1,
//     display: "inline-block",
//     direction: "down",
//     colour: orange,
//     word: "tutorials",
//   },
//   {
//     text: "t",
//     left: 15,
//     top: 30.35,
//     display: "inline-block",
//     direction: "down",
//     colour: orange,
//     word: "tutorials",
//     colour2: green,
//     word2: "contact",
//   },
//   {
//     text: "or",
//     left: 15,
//     top: 36.5,
//     display: "inline-block",
//     direction: "down",
//     colour: orange,
//     word: "tutorials",
//   },
//   {
//     text: "i",
//     left: 15,
//     top: 48.9,
//     display: "inline-block",
//     direction: "down",
//     colour: orange,
//     word: "tutorials",
//     colour2: purple,
//     word2: "mission",
//   },
//   {
//     text: "als",
//     left: 15,
//     top: 55.1,
//     display: "inline-block",
//     direction: "down",
//     colour: orange,
//     word: "tutorials",
//   },
//   {
//     text: "c",
//     left: 7.5,
//     top: 30.35,
//     display: "inline-block",
//     direction: "across",
//     colour: green,
//     word: "contact",
//     colour2: goldenrod,
//     word2: "cv",
//   },
//   {
//     text: "on",
//     left: 10.0,
//     top: 30.35,
//     display: "inline-block",
//     direction: "across",
//     colour: green,
//     word: "contact",
//   },
//   {
//     text: "act",
//     left: 17.5,
//     top: 30.35,
//     display: "inline-block",
//     direction: "across",
//     colour: green,
//     word: "contact",
//   },
//   {
//     text: "v",
//     left: 7.5,
//     top: 36.5,
//     display: "inline-block",
//     direction: "down",
//     colour: goldenrod,
//     word: "cv",
//   },
//   {
//     text: "a",
//     left: 32.5,
//     top: 11.82,
//     display: "inline-block",
//     direction: "down",
//     colour: fuschia,
//     word: "articles",
//   },
//   {
//     text: "ticles",
//     left: 32.5,
//     top: 24.1,
//     display: "inline-block",
//     direction: "down",
//     colour: fuschia,
//     word: "articles",
//   },
//   {
//     text: "m",
//     left: 12.5,
//     top: 48.9,
//     display: "inline-block",
//     direction: "across",
//     colour: purple,
//     word: "mission",
//   },
//   {
//     text: "ssion",
//     left: 17.5,
//     top: 48.9,
//     display: "inline-block",
//     direction: "across",
//     colour: purple,
//     word: "mission",
//   },
// ]

export default headingData
